# Source .tmux.conf as suggested in `man tmux`
unbind r
bind r source-file ~/.tmux.conf

# Set prefix key as ctrl + s (caps lock is binded as ctrl)
set -g prefix C-s

# Easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

# Resize using mouse 
set -g mouse on

# Vim like navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U 
bind-key l select-pane -R

# Move status bar to the top
set -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Continuum: auto-save every 30 min, auto-restore on tmux start
set -g @continuum-restore 'on'
set -g @continuum-save-interval '30'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
